In [1]:
import numpy as np
import pandas as pd

In [2]:
loan_data_backup = pd.read_csv('/Users/eileending/Downloads/loan_data_2007_2014.csv')

/var/folders/c5/wvvvdbz52918llrn89472ywr0000gp/T/ipykernel_14486/3050374214.py:1: DtypeWarning: Columns (0: desc) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv('/Users/eileending/Downloads/loan_data_2007_2014.csv')

In [3]:
loan_data = loan_data_backup.copy()

In [4]:
pd.options.display.max_columns=None
loan_data.head(10)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10+ years,RENT,24000.0,Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,< 1 year,RENT,30000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10+ years,RENT,12252.0,Not Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10+ years,RENT,49200.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1 year,RENT,80000.0,Source Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,5,1075269,1311441,5000,5000,5000.0,36 months,7.90,156.46,A,A4,Veolia Transportaton,3 years,RENT,36000.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,My wedding loan I promise to pay back,852xx,AZ,11.20,0.0,Nov-04,3.0,NaN,NaN,9.0,0.0,7963,28.3,12.0,f,0.00,0.00,5631.377753,5631.38,5000.00,631.38,0.00,0.00,0.00,Jan-15,161.03,NaN,Sep-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,6,1069639,1304742,7000,7000,7000.0,60 months,15.96,170.08,C,C5,Southern Star Photography,8 years,RENT,47004.0,Not Verified,Dec-11,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/18/11 > I am planning o...,debt_consolidation,Loan,280xx,NC,23.51,0.0,Jul-05,1.0,NaN,NaN,7.0,0.0,17726,85.6,11.0,f,1889.15,1889.15,8136.840000,8136.84,5110.85,3025.99,0.00,0.00,0.00,Jan-16,170.08,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,7,1072053,1288686,3000,3000,3000.0,36 months,18.64,109.43,E,E1,MKC Accounting,9 years,RENT,48000.0,Source Verified,Dec-11,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Downpayment for...,car,Car Downpayment,900xx,CA,5.35,0.0,Jan-07,2.0,NaN,NaN,4.0,0.0,8221,87.5,4.0,f,0.00,0.00,3938.144334,3938.14,3000.00,938.14,0.00,0.00,0.00,Jan-15,111.34,NaN,Dec-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,8,1071795,1306957,5600,5600,5600.0,60 months,21.28,152.39,F,F2,NaN,4 years,OWN,40000.0,Source Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I own a small h...,small_business,Expand Business & Buy Debt Portfolio,958xx,CA,5.55,0.0,Apr-04,2.0,NaN,NaN,11.0,0.0,5210,32.6,13.0,f,0.00,0.00,646.020000,646.02,162.02,294.94,0.00,189.06,2.09,Apr-12,152.39,NaN,Aug-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,9,1071570,1306721,5375,5375,5350.0,60 months,12.69,121.45,B,B5,Starbucks,< 1 year,RENT,15000.0,Verified,Dec-11,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I'm trying to b...,other,Building my credit history.,774xx,TX,18.08,0.0,Sep-04,0.0,NaN,NaN,2.0,0.0,9279,36.5,3.0,f,0.00,0.00,1476.190000,1469.34,673.48,533.42,0.00,269.29,2.52,Nov-12,121.45,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
loan_data.info()

<class 'pandas.DataFrame'>
RangeIndex: 466285 entries, 0 to 466284
Data columns (total 75 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Unnamed: 0                   466285 non-null  int64
 1   id                           466285 non-null  int64
 2   member_id                    466285 non-null  int64
 3   loan_amnt                    466285 non-null  int64
 4   funded_amnt                  466285 non-null  int64
 5   funded_amnt_inv              466285 non-null  float64
 6   term                         466285 non-null  str
 7   int_rate                     466285 non-null  float64
 8   installment                  466285 non-null  float64
 9   grade                        466285 non-null  str
 10  sub_grade                    466285 non-null  str
 11  emp_title                    438697 non-null  str
 12  emp_length                   445277 non-null  str
 13  home_ownership               466285 non-null  str
 14  annual_inc                   466281 non-null  float64
 15  verification_status          466285 non-null  str
 16  issue_d                      466285 non-null  str
 17  loan_status                  466285 non-null  str
 18  pymnt_plan                   466285 non-null  str
 19  url                          466285 non-null  str
 20  desc                         125981 non-null  str
 21  purpose                      466285 non-null  str
 22  title                        466264 non-null  str
 23  zip_code                     466285 non-null  str
 24  addr_state                   466285 non-null  str
 25  dti                          466285 non-null  float64
 26  delinq_2yrs                  466256 non-null  float64
 27  earliest_cr_line             466256 non-null  str
 28  inq_last_6mths               466256 non-null  float64
 29  mths_since_last_delinq       215934 non-null  float64
 30  mths_since_last_record       62638 non-null   float64
 31  open_acc                     466256 non-null  float64
 32  pub_rec                      466256 non-null  float64
 33  revol_bal                    466285 non-null  int64
 34  revol_util                   465945 non-null  float64
 35  total_acc                    466256 non-null  float64
 36  initial_list_status          466285 non-null  str
 37  out_prncp                    466285 non-null  float64
 38  out_prncp_inv                466285 non-null  float64
 39  total_pymnt                  466285 non-null  float64
 40  total_pymnt_inv              466285 non-null  float64
 41  total_rec_prncp              466285 non-null  float64
 42  total_rec_int                466285 non-null  float64
 43  total_rec_late_fee           466285 non-null  float64
 44  recoveries                   466285 non-null  float64
 45  collection_recovery_fee      466285 non-null  float64
 46  last_pymnt_d                 465909 non-null  str
 47  last_pymnt_amnt              466285 non-null  float64
 48  next_pymnt_d                 239071 non-null  str
 49  last_credit_pull_d           466243 non-null  str
 50  collections_12_mths_ex_med   466140 non-null  float64
 51  mths_since_last_major_derog  98974 non-null   float64
 52  policy_code                  466285 non-null  int64
 53  application_type             466285 non-null  str
 54  annual_inc_joint             0 non-null       float64
 55  dti_joint                    0 non-null       float64
 56  verification_status_joint    0 non-null       float64
 57  acc_now_delinq               466256 non-null  float64
 58  tot_coll_amt                 396009 non-null  float64
 59  tot_cur_bal                  396009 non-null  float64
 60  open_acc_6m                  0 non-null       float64
 61  open_il_6m                   0 non-null       float64
 62  open_il_12m                  0 non-null       float64
 63  open_il_24m                  0 non-null       float64
 64  mths_since_rcnt_il           0 non-null       float64
 65  total_bal_il                 0 non-null       float64
 66  il_util                      0 non-null       float64
 67  open_rv_12m                  0 non-null       float64
 68  open_rv_24m                  0 non-null       float64
 69  max_bal_bc                   0 non-null       float64
 70  all_util                     0 non-null       float64
 71  total_rev_hi_lim             396009 non-null  float64
 72  inq_fi                       0 non-null       float64
 73  total_cu_tl                  0 non-null       float64
 74  inq_last_12m                 0 non-null       float64
dtypes: float64(46), int64(7), str(22)
memory usage: 266.8 MB

# Data processing and manipulation

In [6]:
# change of dates and month
# variables to use:
# ['emp_length_int'],['term_int'], ['mths_since_earlist_crline'], ['mths_since_issued']

In [7]:
# employement lenght
loan_data['emp_length'].unique()

<StringArray>
['10+ years',  '< 1 year',    '1 year',   '3 years',   '8 years',   '9 years',
   '4 years',   '5 years',   '6 years',   '2 years',   '7 years',         nan]
Length: 12, dtype: str

In [8]:
loan_data['emp_length'] = loan_data['emp_length'].str.replace('< 1 year', '0 years')
loan_data['emp_length'] = loan_data['emp_length'].str.extract(r'(\d+)').astype('Int64')

In [9]:
loan_data['emp_length'].unique()

<IntegerArray>
[10, 0, 1, 3, 8, 9, 4, 5, 6, 2, 7, <NA>]
Length: 12, dtype: Int64

In [10]:
loan_data['emp_length_int'] = loan_data['emp_length'].astype('float64')

In [11]:
loan_data['emp_length_int'].unique()

array([10.,  0.,  1.,  3.,  8.,  9.,  4.,  5.,  6.,  2.,  7., nan])

In [12]:
# term length of the loan
loan_data['term'].unique()

<StringArray>
[' 36 months', ' 60 months']
Length: 2, dtype: str

In [13]:
loan_data['term_int'] = loan_data['term'].str.extract(r'(\d+)').astype('Int64')

In [14]:
loan_data['term_int'].unique()

<IntegerArray>
[36, 60]
Length: 2, dtype: Int64

In [15]:
# earlist time client having the credit line with us
loan_data['earliest_cr_line'].unique()

<StringArray>
['Jan-85', 'Apr-99', 'Nov-01', 'Feb-96', 'Jan-96', 'Nov-04', 'Jul-05',
 'Jan-07', 'Apr-04', 'Sep-04',
 ...
 'Jan-54', 'Jan-57', 'Jan-44', 'Oct-50', 'Jan-48', 'Jul-61', 'May-58',
 'Jan-53', 'May-50', 'Nov-56']
Length: 665, dtype: str

In [16]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(loan_data['earliest_cr_line'],format='%b-%y')

In [17]:
loan_data['earliest_cr_line_date']

0        1985-01-01
1        1999-04-01
2        2001-11-01
3        1996-02-01
4        1996-01-01
            ...
466280   2003-04-01
466281   1997-06-01
466282   2001-12-01
466283   2003-02-01
466284   2000-02-01
Name: earliest_cr_line_date, Length: 466285, dtype: datetime64[us]

In [18]:
from datetime import date
today = date.today()
print(today)

2026-08-31

In [19]:
# use the '2017-12-01' as instructed in the course, as the data is old
# np.timedelta64 not supported, changed another way

ref_date = pd.to_datetime('2017-12-01')
loan_data['mths_since_earlist_crline'] = (
    (ref_date.year - loan_data['earliest_cr_line_date'].dt.year)*12 + 
    (ref_date.month - loan_data['earliest_cr_line_date'].dt.month)
    ).astype('float64')

In [20]:
loan_data['mths_since_earlist_crline'].describe()

count    466256.000000
mean        239.482430
std          93.974829
min        -612.000000
25%         183.000000
50%         225.000000
75%         285.000000
max         587.000000
Name: mths_since_earlist_crline, dtype: float64

In [21]:
# find the negative, why
test_date = loan_data.loc[:,['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earlist_crline']][loan_data['mths_since_earlist_crline']<0]

In [22]:
loan_data.loc[:,['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earlist_crline']][loan_data['mths_since_earlist_crline']==587]

       earliest_cr_line earliest_cr_line_date  mths_since_earlist_crline
61350            Jan-69            1969-01-01                      587.0
70333            Jan-69            1969-01-01                      587.0
93221            Jan-69            1969-01-01                      587.0
132336           Jan-69            1969-01-01                      587.0
137669           Jan-69            1969-01-01                      587.0
197707           Jan-69            1969-01-01                      587.0
206366           Jan-69            1969-01-01                      587.0
213120           Jan-69            1969-01-01                      587.0
224077           Jan-69            1969-01-01                      587.0
235417           Jan-69            1969-01-01                      587.0
235597           Jan-69            1969-01-01                      587.0
240250           Jan-69            1969-01-01                      587.0
240954           Jan-69            1969-01-01                      587.0
263147           Jan-69            1969-01-01                      587.0
263632           Jan-69            1969-01-01                      587.0
265070           Jan-69            1969-01-01                      587.0
290782           Jan-69            1969-01-01                      587.0
304671           Jan-69            1969-01-01                      587.0
316795           Jan-69            1969-01-01                      587.0
344032           Jan-69            1969-01-01                      587.0
351366           Jan-69            1969-01-01                      587.0
364003           Jan-69            1969-01-01                      587.0
366941           Jan-69            1969-01-01                      587.0
372347           Jan-69            1969-01-01                      587.0
374204           Jan-69            1969-01-01                      587.0
379797           Jan-69            1969-01-01                      587.0
379976           Jan-69            1969-01-01                      587.0
380611           Jan-69            1969-01-01                      587.0
380659           Jan-69            1969-01-01                      587.0
392860           Jan-69            1969-01-01                      587.0
398309           Jan-69            1969-01-01                      587.0
402353           Jan-69            1969-01-01                      587.0
402607           Jan-69            1969-01-01                      587.0
404065           Jan-69            1969-01-01                      587.0
413162           Jan-69            1969-01-01                      587.0
440626           Jan-69            1969-01-01                      587.0
442848           Jan-69            1969-01-01                      587.0
449585           Jan-69            1969-01-01                      587.0
455828           Jan-69            1969-01-01                      587.0
465770           Jan-69            1969-01-01                      587.0

In [23]:
# test if all the negative ones are due to wrongfully get dates in 60s earlier than 69
test_date['earliest_cr_line'].str.extract(r'(\d+)')[0].unique()

<StringArray>
['62', '68', '64', '67', '65', '63', '54', '66', '59', '56', '46', '50', '61',
 '60', '57', '53', '55', '51', '58', '49', '44', '48']
Length: 22, dtype: str

In [24]:
# confirmed they are all smaller than 69, which is the earliest date, so assign the same date to them 
# to achieve the most recent approach as the data is too old from the date of 2017

loan_data.loc[loan_data['mths_since_earlist_crline']<0, 'mths_since_earlist_crline']=loan_data['mths_since_earlist_crline'].max()

In [25]:
loan_data['mths_since_earlist_crline'].describe()

count    466256.000000
mean        242.385374
std          86.460310
min          73.000000
25%         184.000000
50%         226.000000
75%         285.000000
max         587.000000
Name: mths_since_earlist_crline, dtype: float64

In [26]:
pd.qcut(loan_data['mths_since_earlist_crline'],q=4).value_counts().sort_index()
#almost equal in each bucket

mths_since_earlist_crline
(72.999, 184.0]    119365
(184.0, 226.0]     115772
(226.0, 285.0]     114687
(285.0, 587.0]     116432
Name: count, dtype: int64

In [27]:
# issue date manipulation
loan_data['issue_d'].unique()

<StringArray>
['Dec-11', 'Nov-11', 'Oct-11', 'Sep-11', 'Aug-11', 'Jul-11', 'Jun-11',
 'May-11', 'Apr-11', 'Mar-11', 'Feb-11', 'Jan-11', 'Dec-10', 'Nov-10',
 'Oct-10', 'Sep-10', 'Aug-10', 'Jul-10', 'Jun-10', 'May-10', 'Apr-10',
 'Mar-10', 'Feb-10', 'Jan-10', 'Dec-09', 'Nov-09', 'Oct-09', 'Sep-09',
 'Aug-09', 'Jul-09', 'Jun-09', 'May-09', 'Apr-09', 'Mar-09', 'Feb-09',
 'Jan-09', 'Dec-08', 'Nov-08', 'Oct-08', 'Sep-08', 'Aug-08', 'Jul-08',
 'Jun-08', 'May-08', 'Apr-08', 'Mar-08', 'Feb-08', 'Jan-08', 'Dec-07',
 'Nov-07', 'Oct-07', 'Sep-07', 'Aug-07', 'Jul-07', 'Jun-07', 'Dec-13',
 'Nov-13', 'Oct-13', 'Sep-13', 'Aug-13', 'Jul-13', 'Jun-13', 'May-13',
 'Apr-13', 'Mar-13', 'Feb-13', 'Jan-13', 'Dec-12', 'Nov-12', 'Oct-12',
 'Sep-12', 'Aug-12', 'Jul-12', 'Jun-12', 'May-12', 'Apr-12', 'Mar-12',
 'Feb-12', 'Jan-12', 'Dec-14', 'Nov-14', 'Oct-14', 'Sep-14', 'Aug-14',
 'Jul-14', 'Jun-14', 'May-14', 'Apr-14', 'Mar-14', 'Feb-14', 'Jan-14']
Length: 91, dtype: str

In [28]:
loan_data['issue_d'] = pd.to_datetime(loan_data['issue_d'],format='%b-%y')

# use the same ref date as 2017
ref_date = pd.to_datetime('2017-12-01')
loan_data['mths_since_issued'] = (
    (ref_date.year - loan_data['issue_d'].dt.year)*12 + 
    (ref_date.month - loan_data['issue_d'].dt.month)
    ).astype('float64')

In [29]:
loan_data['mths_since_issued'].describe()

count    466285.000000
mean         51.255187
std          14.340154
min          36.000000
25%          41.000000
50%          47.000000
75%          57.000000
max         126.000000
Name: mths_since_issued, dtype: float64

In [30]:
pd.qcut(loan_data['mths_since_issued'],q=4).value_counts().sort_index()
# similar distribution, with little variation

mths_since_issued
(35.999, 41.0]    132869
(41.0, 47.0]      102759
(47.0, 57.0]      120322
(57.0, 126.0]     110335
Name: count, dtype: int64

In [31]:
# Data Manipulation on Discrete Variables
# binary variables to change to dummies

In [32]:
loan_data['grade'].unique()

<StringArray>
['B', 'C', 'A', 'E', 'F', 'D', 'G']
Length: 7, dtype: str

In [33]:
pd.get_dummies(loan_data['grade'],prefix='grade', dtype=int)

        grade_A  grade_B  grade_C  grade_D  grade_E  grade_F  grade_G
0             0        1        0        0        0        0        0
1             0        0        1        0        0        0        0
2             0        0        1        0        0        0        0
3             0        0        1        0        0        0        0
4             0        1        0        0        0        0        0
...         ...      ...      ...      ...      ...      ...      ...
466280        0        0        1        0        0        0        0
466281        0        0        0        1        0        0        0
466282        0        0        0        1        0        0        0
466283        1        0        0        0        0        0        0
466284        0        0        0        1        0        0        0

[466285 rows x 7 columns]

In [34]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'],prefix='grade', dtype=int),
                     pd.get_dummies(loan_data['sub_grade'],prefix='sub_grade', dtype=int),
                     pd.get_dummies(loan_data['home_ownership'],prefix='home_ownership', dtype=int),
                     pd.get_dummies(loan_data['verification_status'],prefix='verification_status', dtype=int),
                     pd.get_dummies(loan_data['loan_status'],prefix='loan_status', dtype=int),
                     pd.get_dummies(loan_data['purpose'],prefix='purpose', dtype=int),
                     pd.get_dummies(loan_data['addr_state'],prefix='addr_state', dtype=int),
                     pd.get_dummies(loan_data['initial_list_status'],prefix='initial_list_status', dtype=int)]

In [35]:
loan_data_dummies = pd.concat(loan_data_dummies, axis = 1)

In [36]:
loan_data = pd.concat([loan_data,loan_data_dummies], axis=1)

In [37]:
loan_data.head(10)

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,term_int,earliest_cr_line_date,mths_since_earlist_crline,mths_since_issued,grade_A,grade_B,grade_C,grade_D,grade_E,grade_F,grade_G,sub_grade_A1,sub_grade_A2,sub_grade_A3,sub_grade_A4,sub_grade_A5,sub_grade_B1,sub_grade_B2,sub_grade_B3,sub_grade_B4,sub_grade_B5,sub_grade_C1,sub_grade_C2,sub_grade_C3,sub_grade_C4,sub_grade_C5,sub_grade_D1,sub_grade_D2,sub_grade_D3,sub_grade_D4,sub_grade_D5,sub_grade_E1,sub_grade_E2,sub_grade_E3,sub_grade_E4,sub_grade_E5,sub_grade_F1,sub_grade_F2,sub_grade_F3,sub_grade_F4,sub_grade_F5,sub_grade_G1,sub_grade_G2,sub_grade_G3,sub_grade_G4,sub_grade_G5,home_ownership_ANY,home_ownership_MORTGAGE,home_ownership_NONE,home_ownership_OTHER,home_ownership_OWN,home_ownership_RENT,verification_status_Not Verified,verification_status_Source Verified,verification_status_Verified,loan_status_Charged Off,loan_status_Current,loan_status_Default,loan_status_Does not meet the credit policy. Status:Charged Off,loan_status_Does not meet the credit policy. Status:Fully Paid,loan_status_Fully Paid,loan_status_In Grace Period,loan_status_Late (16-30 days),loan_status_Late (31-120 days),purpose_car,purpose_credit_card,purpose_debt_consolidation,purpose_educational,purpose_home_improvement,purpose_house,purpose_major_purchase,purpose_medical,purpose_moving,purpose_other,purpose_renewable_energy,purpose_small_business,purpose_vacation,purpose_wedding,addr_state_AK,addr_state_AL,addr_state_AR,addr_state_AZ,addr_state_CA,addr_state_CO,addr_state_CT,addr_state_DC,addr_state_DE,addr_state_FL,addr_state_GA,addr_state_HI,addr_state_IA,addr_state_ID,addr_state_IL,addr_state_IN,addr_state_KS,addr_state_KY,addr_state_LA,addr_state_MA,addr_state_MD,addr_state_ME,addr_state_MI,addr_state_MN,addr_state_MO,addr_state_MS,addr_state_MT,addr_state_NC,addr_state_NE,addr_state_NH,addr_state_NJ,addr_state_NM,addr_state_NV,addr_state_NY,addr_state_OH,addr_state_OK,addr_state_OR,addr_state_PA,addr_state_RI,addr_state_SC,addr_state_SD,addr_state_TN,addr_state_TX,addr_state_UT,addr_state_VA,addr_state_VT,addr_state_WA,addr_state_WI,addr_state_WV,addr_state_WY,initial_list_status_f,initial_list_status_w
0,0,1077501,1296599,5000,5000,4975.0,36 months,10.65,162.87,B,B2,NaN,10,RENT,24000.0,Verified,2011-12-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I need to upgra...,credit_card,Computer,860xx,AZ,27.65,0.0,Jan-85,1.0,NaN,NaN,3.0,0.0,13648,83.7,9.0,f,0.00,0.00,5861.071414,5831.78,5000.00,861.07,0.00,0.00,0.00,Jan-15,171.62,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,36,1985-01-01,395.0,72.0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
1,1,1077430,1314167,2500,2500,2500.0,60 months,15.27,59.83,C,C4,Ryder,0,RENT,30000.0,Source Verified,2011-12-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/22/11 > I plan to use t...,car,bike,309xx,GA,1.00,0.0,Apr-99,5.0,NaN,NaN,3.0,0.0,1687,9.4,4.0,f,0.00,0.00,1008.710000,1008.71,456.46,435.17,0.00,117.08,1.11,Apr-13,119.66,NaN,Sep-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,60,1999-04-01,224.0,72.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
2,2,1077175,1313524,2400,2400,2400.0,36 months,15.96,84.33,C,C5,NaN,10,RENT,12252.0,Not Verified,2011-12-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,small_business,real estate business,606xx,IL,8.72,0.0,Nov-01,2.0,NaN,NaN,2.0,0.0,2956,98.5,10.0,f,0.00,0.00,3003.653644,3003.65,2400.00,603.65,0.00,0.00,0.00,Jun-14,649.91,NaN,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,36,2001-11-01,193.0,72.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
3,3,1076863,1277178,10000,10000,10000.0,36 months,13.49,339.31,C,C1,AIR RESOURCES BOARD,10,RENT,49200.0,Source Verified,2011-12-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > to pay for prop...,other,personel,917xx,CA,20.00,0.0,Feb-96,1.0,35.0,NaN,10.0,0.0,5598,21.0,37.0,f,0.00,0.00,12226.302210,12226.30,10000.00,2209.33,16.97,0.00,0.00,Jan-15,357.48,NaN,Jan-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,36,1996-02-01,262.0,72.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4,4,1075358,1311748,3000,3000,3000.0,60 months,12.69,67.79,B,B5,University Medical Group,1,RENT,80000.0,Source Verified,2011-12-01,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I plan on combi...,other,Personal,972xx,OR,17.94,0.0,Jan-96,0.0,38.0,NaN,15.0,0.0,27783,53.9,38.0,f,766.90,766.90,3242.170000,3242.17,2233.10,1009.07,0.00,0.00,0.00,Jan-16,67.79,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,60,1996-01-01,263.0,72.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
5,5,1075269,1311441,5000,5000,5000.0,36 months,7.90,156.46,A,A4,Veolia Transportaton,3,RENT,36000.0,Source Verified,2011-12-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,NaN,wedding,My wedding loan I promise to pay back,852xx,AZ,11.20,0.0,Nov-04,3.0,NaN,NaN,9.0,0.0,7963,28.3,12.0,f,0.00,0.00,5631.377753,5631.38,5000.00,631.38,0.00,0.00,0.00,Jan-15,161.03,NaN,Sep-15,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,36,2004-11-01,157.0,72.0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
6,6,1069639,1304742,7000,7000,7000.0,60 months,15.96,170.08,C,C5,Southern Star Photography,8,RENT,47004.0,Not Verified,2011-12-01,Current,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/18/11 > I am planning o...,debt_consolidation,Loan,280xx,NC,23.51,0.0,Jul-05,1.0,NaN,NaN,7.0,0.0,17726,85.6,11.0,f,1889.15,1889.15,8136.840000,8136.84,5110.85,3025.99,0.00,0.00,0.00,Jan-16,170.08,Feb-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,60,2005-07-01,149.0,72.0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,7,1072053,1288686,3000,3000,3000.0,36 months,18.64,109.43,E,E1,MKC Accounting,9,RENT,48000.0,Source Verified,2011-12-01,Fully Paid,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > Downpayment for...,car,Car Downpayment,900xx,CA,5.35,0.0,Jan-07,2.0,NaN,NaN,4.0,0.0,8221,87.5,4.0,f,0.00,0.00,3938.144334,3938.14,3000.00,938.14,0.00,0.00,0.00,Jan-15,111.34,NaN,Dec-14,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,36,2007-01-01,131.0,72.0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
8,8,1071795,1306957,5600,5600,5600.0,60 months,21.28,152.39,F,F2,NaN,4,OWN,40000.0,Source Verified,2011-12-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/21/11 > I own a small h...,small_business,Expand Business & Buy Debt Portfolio,958xx,CA,5.55,0.0,Apr-04,2.0,NaN,NaN,11.0,0.0,5210,32.6,13.0,f,0.00,0.00,646.020000,646.02,162.02,294.94,0.00,189.06,2.09,Apr-12,152.39,NaN,Aug-12,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,60,2004-04-01,164.0,72.0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
9,9,1071570,1306721,5375,5375,5350.0,60 months,12.69,121.45,B,B5,Starbucks,0,RENT,15000.0,Verified,2011-12-01,Charged Off,n,https://www.lendingclub.com/browse/loanDetail....,Borrower added on 12/16/11 > I'm trying to b...,other,Building my credit history.,774xx,TX,18.08,0.0,Sep-04,0.0,NaN,NaN,2.0,0.0,9279,36.5,3.0,f,0.00,0.00,1476.190000,1469.34,673.48,533.42,0.00,269.29,2.52,Nov-12,121.45,NaN,Mar-13,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,60,2004-09-01,159.0,72.0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0

# Dealing with Missing Values

In [38]:
pd.options.display.max_rows = None
loan_data.isnull().sum()

Unnamed: 0                                                              0
id                                                                      0
member_id                                                               0
loan_amnt                                                               0
funded_amnt                                                             0
funded_amnt_inv                                                         0
term                                                                    0
int_rate                                                                0
installment                                                             0
grade                                                                   0
sub_grade                                                               0
emp_title                                                           27588
emp_length                                                          21008
home_ownership                                                          0
annual_inc                                                              4
verification_status                                                     0
issue_d                                                                 0
loan_status                                                             0
pymnt_plan                                                              0
url                                                                     0
desc                                                               340304
purpose                                                                 0
title                                                                  21
zip_code                                                                0
addr_state                                                              0
dti                                                                     0
delinq_2yrs                                                            29
earliest_cr_line                                                       29
inq_last_6mths                                                         29
mths_since_last_delinq                                             250351
mths_since_last_record                                             403647
open_acc                                                               29
pub_rec                                                                29
revol_bal                                                               0
revol_util                                                            340
total_acc                                                              29
initial_list_status                                                     0
out_prncp                                                               0
out_prncp_inv                                                           0
total_pymnt                                                             0
total_pymnt_inv                                                         0
total_rec_prncp                                                         0
total_rec_int                                                           0
total_rec_late_fee                                                      0
recoveries                                                              0
collection_recovery_fee                                                 0
last_pymnt_d                                                          376
last_pymnt_amnt                                                         0
next_pymnt_d                                                       227214
last_credit_pull_d                                                     42
collections_12_mths_ex_med                                            145
mths_since_last_major_derog                                        367311
policy_code                                                             0
application_type                                                        0
annual_inc_joint                                                   466285
dti_joint                                                          466285
verification_status_joint                                          466285
acc_now_delinq                                                         29
tot_coll_amt                                                        70276
tot_cur_bal                                                         70276
open_acc_6m                                                        466285
open_il_6m                                                         466285
open_il_12m                                                        466285
open_il_24m                                                        466285
mths_since_rcnt_il                                                 466285
total_bal_il                                                       466285
il_util                                                            466285
open_rv_12m                                                        466285
open_rv_24m                                                        466285
max_bal_bc                                                         466285
all_util                                                           466285
total_rev_hi_lim                                                    70276
inq_fi                                                             466285
total_cu_tl                                                        466285
inq_last_12m                                                       466285
emp_length_int                                                      21008
term_int                                                                0
earliest_cr_line_date                                                  29
mths_since_earlist_crline                                              29
mths_since_issued                                                       0
grade_A                                                                 0
grade_B                                                                 0
grade_C                                                                 0
grade_D                                                                 0
grade_E                                                                 0
grade_F                                                                 0
grade_G                                                                 0
sub_grade_A1                                                            0
sub_grade_A2                                                            0
sub_grade_A3                                                            0
sub_grade_A4                                                            0
sub_grade_A5                                                            0
sub_grade_B1                                                            0
sub_grade_B2                                                            0
sub_grade_B3                                                            0
sub_grade_B4                                                            0
sub_grade_B5                                                            0
sub_grade_C1                                                            0
sub_grade_C2                                                            0
sub_grade_C3                                                            0
sub_grade_C4                                                            0
sub_grade_C5                                                            0
sub_grade_D1                                                            0
sub_grade_D2                                                            0
sub_grade_D3                                                            0
sub_grade_D4                                                            0
sub_grade_D5                                                            0
sub_grade_E1                                                            0
sub_grade_E2                                                            0
sub_grade_E3                                                            0
sub_grade_E4                                                            0
sub_grade_E5                                                            0
sub_grade_F1                                                            0
sub_grade_F2                                                            0
sub_grade_F3                                                            0
sub_grade_F4                                                            0
sub_grade_F5                                                            0
sub_grade_G1                                                            0
sub_grade_G2                                                            0
sub_grade_G3                                                            0
sub_grade_G4                                                            0
sub_grade_G5                                                            0
home_ownership_ANY                                                      0
home_ownership_MORTGAGE                                                 0
home_ownership_NONE                                                     0
home_ownership_OTHER                                                    0
home_ownership_OWN                                                      0
home_ownership_RENT                                                     0
verification_status_Not Verified                                        0
verification_status_Source Verified                                     0
verification_status_Verified                                            0
loan_status_Charged Off                                                 0
loan_status_Current                                                     0
loan_status_Default                                                     0
loan_status_Does not meet the credit policy. Status:Charged Off         0
loan_status_Does not meet the credit policy. Status:Fully Paid          0
loan_status_Fully Paid                                                  0
loan_status_In Grace Period                                             0
loan_status_Late (16-30 days)                                           0
loan_status_Late (31-120 days)                                          0
purpose_car                                                             0
purpose_credit_card                                                     0
purpose_debt_consolidation                                              0
purpose_educational                                                     0
purpose_home_improvement                                                0
purpose_house                                                           0
purpose_major_purchase                                                  0
purpose_medical                                                         0
purpose_moving                                                          0
purpose_other                                                           0
purpose_renewable_energy                                                0
purpose_small_business                                                  0
purpose_vacation                                                        0
purpose_wedding                                                         0
addr_state_AK                                                           0
addr_state_AL                                                           0
addr_state_AR                                                           0
addr_state_AZ                                                           0
addr_state_CA                                                           0
addr_state_CO                                                           0
addr_state_CT                                                           0
addr_state_DC                                                           0
addr_state_DE                                                           0
addr_state_FL                                                           0
addr_state_GA                                                           0
addr_state_HI                                                           0
addr_state_IA                                                           0
addr_state_ID                                                           0
addr_state_IL                                                           0
addr_state_IN                                                           0
addr_state_KS                                                           0
addr_state_KY                                                           0
addr_state_LA                                                           0
addr_state_MA                                                           0
addr_state_MD                                                           0
addr_state_ME                                                           0
addr_state_MI                                                           0
addr_state_MN                                                           0
addr_state_MO                                                           0
addr_state_MS                                                           0
addr_state_MT                                                           0
addr_state_NC                                                           0
addr_state_NE                                                           0
addr_state_NH                                                           0
addr_state_NJ                                                           0
addr_state_NM                                                           0
addr_state_NV                                                           0
addr_state_NY                                                           0
addr_state_OH                                                           0
addr_state_OK                                                           0
addr_state_OR                                                           0
addr_state_PA                                                           0
addr_state_RI                                                           0
addr_state_SC                                                           0
addr_state_SD                                                           0
addr_state_TN                                                           0
addr_state_TX                                                           0
addr_state_UT                                                           0
addr_state_VA                                                           0
addr_state_VT                                                           0
addr_state_WA                                                           0
addr_state_WI                                                           0
addr_state_WV                                                           0
addr_state_WY                                                           0
initial_list_status_f                                                   0
initial_list_status_w                                                   0
dtype: int64

In [39]:
loan_data['total_rev_hi_lim'] = loan_data['total_rev_hi_lim'].fillna(loan_data['funded_amnt'])

In [40]:
loan_data['annual_inc']= loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean())

In [41]:
loan_data['mths_since_earlist_crline'] = loan_data['mths_since_earlist_crline'].fillna(0)

In [42]:
cols = [
    'acc_now_delinq',
    'total_acc',
    'pub_rec',
    'open_acc',
    'inq_last_6mths',
    'delinq_2yrs',
    'emp_length_int'
]

loan_data[cols] = loan_data[cols].fillna(0)

# PD Model

In [43]:
# get the target (0 = default, 1 = non-default)

In [44]:
loan_data['loan_status'].unique()

<StringArray>
[                                         'Fully Paid',
                                         'Charged Off',
                                             'Current',
                                             'Default',
                                  'Late (31-120 days)',
                                     'In Grace Period',
                                   'Late (16-30 days)',
  'Does not meet the credit policy. Status:Fully Paid',
 'Does not meet the credit policy. Status:Charged Off']
Length: 9, dtype: str

In [45]:
loan_data['loan_status'].value_counts()/loan_data['loan_status'].count()

loan_status
Current                                                0.480878
Fully Paid                                             0.396193
Charged Off                                            0.091092
Late (31-120 days)                                     0.014798
In Grace Period                                        0.006747
Does not meet the credit policy. Status:Fully Paid     0.004263
Late (16-30 days)                                      0.002612
Default                                                0.001784
Does not meet the credit policy. Status:Charged Off    0.001632
Name: count, dtype: float64

In [46]:
list_default = ['Charged Off', 'Default','Does not meet the credit policy. Status:Charged Off','Late (31-120 days)']

In [47]:
loan_data['good_bad'] = np.where(loan_data['loan_status'].isin(list_default),0,1)

# Splitting Data

In [48]:
from sklearn.model_selection import train_test_split

In [49]:
input_train, input_test, target_train, target_test = train_test_split(loan_data.drop('good_bad',axis=1),loan_data['good_bad'], test_size=0.2, random_state = 42)

In [ ]:
# save these to local for later use

In [54]:
input_train.to_pickle('/Users/eileending/Downloads/input_train.pkl')
input_test.to_pickle('/Users/eileending/Downloads/input_test.pkl')
target_train.to_pickle('/Users/eileending/Downloads/target_train.pkl')
target_test.to_pickle('/Users/eileending/Downloads/target_test.pkl')